'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("RubiksCubeSolver_v2_0.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to //
        '''
        '''#if __VERSION__ == 330
        '''
        '''	in vec4 vertexColor; // The input variable from the vertex shader (same name and same type)
        '''	in vec3 pos;
        '''
        '''	uniform vec4 lightColor; // = vec4(0.9, 0.2, 0.9, 1.0);
        '''	uniform float ambientStrength;
        '''	//uniform vec3 worldPosition;
        '''	uniform float pad;
        '''	uniform mat4 colourMat;
        '''
        '''	out vec4 color;
        '''
        '''	void main()
        '''	{
        '''		
        '''		vec3 worldPosition = vec3(colourMat * vec4(pos, 1.0f));
        '''
        '''		//if ((pos.x != 0 || worldPosition.x &lt;= (-1.5 - pad)) &amp;&amp; (pos.x != 1 || worldPosition.x &gt;= ( [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property fragmentShader() As String
            Get
                Return ResourceManager.GetString("fragmentShader", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property happyIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("happyIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property infoIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("infoIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property settingsIcon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("settingsIcon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to //
        '''
        '''#if __VERSION__ == 330
        '''
        '''	layout (location = 0) in vec3 position; //VAttPointer 0
        '''	layout (location = 1) in vec4 color; //VAttPointer 1
        '''	layout (location = 2) in vec3 normal;
        '''
        '''	uniform mat4 model;
        '''	uniform mat4 view;
        '''	uniform mat4 projection;
        '''
        '''
        '''	out vec4 vertexColor;
        '''	out vec3 pos;
        '''	//out vec3 worldPos;
        '''
        '''	void main()
        '''	{
        '''		gl_Position = projection * view * model * vec4(position, 1.0f);	
        '''		vertexColor = color;
        '''		//worldPos = vec3(model * vec4(position, 1.0f));
        '''		pos = position;
        '''	}
        '''# [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property vertexShader() As String
            Get
                Return ResourceManager.GetString("vertexShader", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
